<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\PortfolioTranslation;

class UpdatePortfolioResultsSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        
        $portfolioResults = [
            // Nur Plastik (ID: 95)
            95 => [
                'ru' => '<p>Мы собрали чистый, лаконичный сайт, в котором есть всё необходимое: продукция с качественными фото, рассказ о производстве, контактная форма и мессенджеры для связи. Сделали многоязычную версию — чтобы зарубежные партнёры не терялись в догадках. Упор сделали не на "красоту ради красоты", а на простоту, доверие и ясность. Теперь у клиента есть инструмент, который помогает выстраивать первые деловые контакты — и уверенно презентовать компанию на международной арене.</p>',
                'en' => '<p>We created a clean, laconic website that has everything needed: products with quality photos, production story, contact form and messengers for communication. We made a multilingual version — so that foreign partners don\'t get lost in guesses. We focused not on "beauty for beauty\'s sake", but on simplicity, trust and clarity. Now the client has a tool that helps build first business contacts — and confidently present the company on the international arena.</p>',
                'tm' => '<p>Biz arassa, lakoniki sahypa döretdik, ol ähli zerur zatlary öz içine alýar: hilili suratlar bilen önümler, öndüriliş taryhy, aragatnaşyk formasy we habarlaşmak üçin messenjerler. Köp dilli wersiýa döretdik — daşarky hyzmatdaşlaryň düşnüksiz galmazlygy üçin. "Gözellik üçin gözellik" däl-de, eýsem ýönekeýlik, ynam we aýdyňlyk üstünde işledik. Indi müşderiniň ilkinji iş aragatnaşyklary gurmaga we kompaniýany halkara sahnada ynamly tanyşdyrmaga kömek edýän guraly bar.</p>'
            ],
            // Atto (ID: 99)
            99 => [
                'ru' => '<p>Мы разработали мобильное приложение для покупателей — лёгкое, понятное и стильное. Там удобно листать каталог, смотреть фотографии, добавлять в корзину и оформлять заказ. Параллельно сделали внутреннюю админку — чтобы клиент сам управлял товаром, ценами, акциями и статусами заказов. Без программистов и лишней бюрократии. Система получилась гибкой: всё работает быстро, удобно, без лишнего. А главное — у клиента теперь есть свой собственный онлайн-магазин, который можно развивать как полноценный бренд</p>',
                'en' => '<p>We developed a mobile app for customers — lightweight, intuitive, and stylish. It makes browsing the catalog a pleasure: users can easily scroll through products, view photos, add items to the cart, and place an order with just a few taps. At the same time, we built an internal admin panel — so the client could manage products, prices, promotions, and order statuses independently. No need for developers or bureaucracy. The result is a flexible system: everything runs smoothly, efficiently, and without clutter. Most importantly, the client now has a fully independent online store — a foundation they can grow into a full-fledged brand.</p>',
                'tm' => '<p>Biz müşderiler üçin ýeňil, düşnükli we döwrebap mobil goşundy taýýarladyk. Ulanyjylar katalogy aňsatlyk bilen gözden geçirip, suratlara seredip, harytlary sebede goşup we sargyt edip bilýärler. Şonuň bilen birlikde, müşderiniň özüniň harytlary, bahalary, aksiýalary we sargytlaryň ýagdaýlaryny dolandyrmagy üçin içerki admin panelini döretdik. Programmistlere ýa-da artykmaç resminama işlerine zerurlyk galmady. Netijede çeýe we amatly ulgam döredi: hemme zat çalt we ýönekeý işleýär. Iň möhümi — müşderiniň häzirki wagtda özüniň garaşsyz onlaýn dükanı bar we ol bu platformany doly derejeli brende öwürip biler.</p>'
            ],
            // TM Uber (ID: 101)
            101 => [
                'ru' => '<p>Мы разработали полноценный комплекс: Веб-диспетчерская — позволяет вручную управлять заказами, отслеживать поездки, назначать водителей и смотреть аналитику. Интерфейс простой, без перегрузки. Приложение для водителя — показывает заказы, маршрут, текущий баланс и статус. Водителю не нужно "привыкать" — всё логично с первого дня. Приложение для клиента — с минималистичным дизайном и быстрым оформлением заказа. Адрес, комментарий, один клик — машина уже едет. Система построена так, чтобы её можно было дополнять, улучшать, адаптировать под локальные особенности. Это не шаблон, это — основа для развития полноценного бизнеса с гибким управлением и собственным лицом.</p>',
                'en' => '<p>We built a full-featured system: Web dispatcher panel — allows manual control over orders, trip tracking, driver assignment, and access to analytics. The interface is clean and straightforward — no clutter, no distractions. Driver app — displays active orders, routes, balance, and current status. There\'s no learning curve — everything is intuitive from day one. Client app — features a minimalist design and quick order placement. Enter an address, leave a comment, tap once — your ride is on its way. The system is designed to be extendable, upgradable, and adaptable to local specifics. This isn\'t a cookie-cutter template — it\'s a foundation for building a real business with flexible management and a unique identity.</p>',
                'tm' => '<p>Biz müşderi üçin doly taýýar çözgüt işläp taýýarladyk: Web-dispetçer paneli — sargytlary el bilen dolandyrmaga, ýolagçy gatnawlaryny yzarlamaga, sürüjileri bellemäge we statistikalary görmäge mümkinçilik berýär. Interfesi düşnükli, ýönekeý — hiç zat artyk däl. Sürüji üçin goşundy — sargytlar, ugur, balans we ýagdaý görkezilýär. Sürüji üçin hiç hili öwrenmäge zerurlyk ýok — ähli zat başyndan logiki we düşnükli. Müşderi üçin goşundy — minimalistik dizaýn bilen, sargyt goýmagyň iň çalt we ýönekeý görnüşi. Salgy girizilýär, bellik ýazylýar, bir gezek basylýar — ulag ýola çykýar. Ulgam soňraky ösüş, täzelenme we ýerli aýratynlyklara uýgunlaşma üçin ýörite gurlan. Bu taýýar şablon däl — bu öz brendiňi gurmaga niýetlenen güýçli binyat.</p>'
            ],
            // Duomouseion (ID: 102)
            102 => [
                'ru' => '<p>Мы разработали элегантный и лаконичный сайт, который стал онлайн-пространством дуэта. Добавили раздел с афишей: даты, площадки, города, ссылки на покупку билетов — всё, что нужно, чтобы не пропустить ближайшее выступление. Также предусмотрели возможность подписки и обратной связи. Сайт адаптивный, работает на французском языке и одинаково удобно отображается на любых устройствах. Клиент сам может обновлять расписание и вносить изменения без участия разработчиков. Теперь у DuoMouseion есть красивый и функциональный сайт, с помощью которого они могут не только информировать, но и деликатно развивать своё творческое присутствие во Франции.</p>',
                'en' => '<p>We created an elegant and minimalist website that became the duo\'s online home. We added a dedicated schedule section: concert dates, venues, cities, and ticket links — everything fans need to stay updated and never miss a performance. We also included options for newsletter subscriptions and direct contact. The website is fully responsive, works in French, and displays beautifully on all devices. The client can update the calendar and make changes on their own — no need for a developer\'s help. Now DuoMouseion has a beautiful and functional website that helps them not only inform their audience, but also subtly grow their artistic presence across France.</p>',
                'tm' => '<p>Biz duetiň döredijilik dünyäsine laýyk gelýän, estetikasy güýçli we sada görnüşli web-saýt taýýarladyk. Bu sahypa olaryň onlaýn giňişligine öwrüldi — muşdaklary bilen gatnaşygy saklamaga, çykyşlar baradaky maglumatlary paýlaşmaga we özleriniň döredijilik keşbini görkezmäge mümkinçilik berýär. Afişa üçin aýratyn bölüm ýerleşdirildi: çykyşlaryň senesi, şäheri, sahnasy we bilet satyn almak üçin baglanyşyklar — tomaşaçylaryň geljekki çykyşlardan habarly bolmagy üçin ähli zat göz öňünde tutuldy. Şeýle-de abuna ýazylmak we göni habarlaşmak mümkinçilikleri döredildi. Sahypa doly adaptirlenen görnüşde işlenildi: fransuz dilinde işleýär we ähli enjamda birmeňzeş derejede amatly görkezilýär. Duet sahypadaky tertibi we maglumatlary özbaşdak täzeläp, islendik üýtgetmeleri girizip bilýär — programmistleriň kömegine garaşsyz. Indi DuoMouseion döredijilik älemindäki gatnaşygyny has çuňlaşdyryp bilýän owadan hem-de peýdaly sahypa eýe boldy — olaryň sahnalaýyn keşbini duýgurlyk bilen görkezýän aýratyn giňişlik.</p>'
            ],
            // Nidzhat (ID: 103)
            103 => [
                'ru' => '<p>Мы разработали сайт, который помогает юристу говорить с клиентами на одном языке. Структура продумана так, чтобы посетитель легко находил нужную информацию: отдельные страницы для основных направлений практики, раздел с ответами на частые вопросы, блок с личной историей и подходом к делу, контакты с удобной формой и быстрыми мессенджерами. Дизайн — сдержанный и современный, без излишеств, но с акцентом на детали. Сайт одинаково удобно работает на всех устройствах и легко масштабируется под новые разделы или услуги. Теперь у Nidzhat есть профессиональное онлайн-представительство, которое работает на доверие, помогает формировать очередь на консультации и усиливает личный бренд в юридической сфере.</p>',
                'en' => '<p>We created a website that helps the lawyer speak the same language as their clients. The structure is thoughtfully designed so that visitors can easily find what they\'re looking for: dedicated pages for key legal practice areas, a section with answers to frequently asked questions, a block with the lawyer\'s personal story and approach, contact options with a simple form and quick-access messengers. The design is modern and restrained — no excess, but with careful attention to detail. The site works smoothly across all devices and scales easily for future sections or services. Now, Nidzhat has a professional online presence that builds trust, attracts a steady stream of consultations, and strengthens his personal brand in the legal field.</p>',
                'tm' => '<p>Biz müşderiniň müşderileri bilен bir dilde gürleşmegine köмek edýän sahypa döretdik. Sahypanyň gurluşy islendik ulanyjy gerek bolan maglumatyny aňsatlyk bilen tapyp biler ýaly gurnalan: hukuk hyzmatlarynyň esasy ugurlary üçin aýratyn sahypalar, köp berilýän soraglara jogap berýän bölüm, şahsy taryh we iş ýörelgesi bilen tanyşdyrýan blok, halkarasy amatly, tiz habarlaşyk serişdeleri bilen üpjün edilen kontaktlar bölümi. Dizaýn — ýönekeý, döwrebap we üns bilen işlenilen. Sahypa ähli enjamda birmeňzeş derejede amatly işleýär we geljekde täze bölümler ýa-da hyzmatlar goşulanda hem aňsatlyk bilen giňeldilip bilner. Indi Nidzhat hukuk ulgamyndaky şahsy brendini berkitmäge, ynam gazanmaga we maslahatlara isleg döredýän professional onlaýn wekiliýete eýe boldy.</p>'
            ],
            // Anima Home (ID: 108)
            108 => [
                'ru' => '<p>Мы разработали Android-приложение, которое стало полноценной частью системы "умного дома". Интерфейс — минималистичный и интуитивный: пользователь может в пару нажатий управлять состояниями устройств, просматривать статусы и получать уведомления. Приложение работает напрямую с оборудованием заказчика и точно передаёт состояния, команды и сценарии. Сделали акцент на UX: управление должно быть понятным и удобным для всех членов семьи, без обучения и сложных инструкций. Теперь пользователи системы Anima Home могут комфортно управлять своим домом прямо со смартфона — быстро, стабильно и красиво.</p>',
                'en' => '<p>We developed an Android app that became a full-fledged part of the smart home system. The interface is minimalist and intuitive — users can control device states, view statuses, and receive notifications with just a few taps. The app communicates directly with the client\'s hardware, accurately transmitting statuses, commands, and automation scenarios. We placed a strong focus on UX: the controls had to be simple and accessible for all family members — with no learning curve or complicated instructions. Now, users of the Anima Home system can comfortably manage their home right from their smartphone — quickly, reliably, and beautifully.</p>',
                'tm' => '<p>Biz "akylly öý" ulgamynyň doly bölegi hökmünde işläp duran Android goşundyny döretdik. Interfeýsi minimalistik we ulanyjy üçin düşnükli — ulanyjy enjam ýagdaýlaryny birnäçe basyş bilen dolandyrýar, statuslary görýär we bildirişler alýar. Goşundy müşderiniň enjamlary bilen göňüden-göni işleýär we ýagdaýlary, komandalary hem-de ssenariýalary takyk geçirýär. Biz ulanyjy tejribesine (UX) aýratyn üns berdik: dolandyryş ähli maşgalanyň agzalary üçin düşnükli bolmaly — hiç hili okuw ýa-da çylşyrymly görkezme gerek däl. Indi Anima Home ulgamynyň ulanyjylary öýlerini telefondan dolandyrmak mümkinçiligine eýe — çalt, durnukly we estetiki taýdan lezzetli görnüşde</p>'
            ],
            // Tulpar (ID: 122)
            122 => [
                'ru' => '<p>Мы с нуля разработали комплексную систему, которая покрывает весь цикл работы сервиса: Админ-панель — для управления маршрутами, расписанием, бронированиями, водителями и аналитикой. Мобильное приложение для водителя — с расписанием рейсов, списками пассажиров и маршрутом. Мобильное приложение для клиента — с возможностью выбрать рейс, забронировать место и получить всю информацию по поездке. Вся система построена так, чтобы её можно было масштабировать на другие города, добавлять новые направления и управлять всем из одного места. У клиента теперь есть готовая цифровая основа для стабильного роста транспортного бизнеса.</p>',
                'en' => '<p>We developed a comprehensive system from scratch that covers the entire service workflow: Admin panel — for managing routes, schedules, bookings, drivers, and analytics. Driver mobile app — with trip schedules, passenger lists, and navigation routes. Customer mobile app — allowing users to select a trip, book a seat, and access all trip details. The entire system is designed to be scalable to other cities, with the ability to add new routes and manage everything from a single platform. The client now has a solid digital foundation for the stable growth of their transportation business.</p>',
                'tm' => '<p>Biz hyzmatyň ähli tapgyrlaryny öz içine alýan döwrebap sanly ulgam döretdik: Admin panel — ugurlary, gatnaw tertiplerini, bronlamalary, sürüjileri we statistikalary dolandyrmak üçin. Sürüji üçin mobil goşundy — gatnaw tertibi, ýolagçy sanawy we ugur bilen üpjün edilýär. Müşderi üçin mobil goşundy — gatnawy saýlamak, ýer bronlamak we ýolagçylyk bilen baglanyşykly ähli maglumatlary almak üçin. Ulgam giňeldilmäge taýýar — täze şäherler, ugurlar goşulyp bilner, ähli dolandyryş bolsa bir ýerde jemlenýär. Müşderi häzirki wagtda işini giňeltmäge mümkinçilik berýän ygtybarly sanly esas gazandy.</p>'
            ],
            // Eurocosmetics (ID: 123)
            123 => [
                'ru' => '<p>Мы разработали одностраничный сайт, адаптированный под фирменный стиль клиента. В дизайне использованы фирменные цвета и визуальные элементы бренда. Сайт содержит: краткую информацию о компании и её продукции, визуальные акценты на товарных линейках, контактные данные для дальнейшей связи. Ресурс адаптирован под мобильные устройства и готов к использованию как на выставке, так и для последующей онлайн-презентации.</p>',
                'en' => '<p>We developed a one-page website aligned with the client\'s brand identity. The design incorporates the brand\'s signature colors and visual elements. The website includes: a brief overview of the company and its products, visual highlights of product lines, contact information for further communication. The website is mobile-friendly and ready to be used both at the exhibition and for future online presentations.</p>',
                'tm' => '<p>Biz müşderiniň korporatiw stili bilen utgaşykly bir sahypalyk web saýty taýýarladyk. Dizaýnda markanyň aýratyn reňkleri we wizual elementleri ulanyldy. Sahypada ýerleşdirildi: kompaniýa we önümleri barada gysgaça maglumat, haryt ugurlaryna degişli wizual bellikler, habarlaşmak üçin aragatnaşyk maglumatlary. Web sahypa mobil enjamlar üçin uýgunlaşdyrylan we ony sergide ýa-da geljekki onlaýn tanyşdyryşlar üçin ulanmak mümkinçiligi bar.</p>'
            ],
            // Nurana Bedew (ID: 124)
            124 => [
                'ru' => '<p>Мы начали с диагностики текущих бизнес-процессов: проанализировали, как в компании строится работа, где происходят задержки и какие задачи дублируются. После этого сформировали план внедрения Bitrix24. В течение одного месяца ежедневно работали с руководителями отделов — настраивали роли, логику задач, маршруты согласования. Затем по цепочке передали систему сотрудникам, обучили работе с ней и сопровождали внедрение. Отдельно разработали кастомные бизнес-процессы, которые автоматизировали: оформление и контроль экспортных операций, внутреннюю легализацию документации, маршруты и статусы согласования контрактов. Теперь у компании — рабочая система на базе Bitrix24, в которой чётко понятно, кто, что и когда делает, где каждый процесс зафиксирован, а важные этапы больше не теряются.</p>',
                'en' => '<p>We started by diagnosing the current business processes: analyzing how work was organized within the company, where delays occurred, and which tasks were duplicated. Based on this, we developed an implementation plan for Bitrix24. For one month, we worked daily with department heads — configuring roles, task logic, and approval workflows. Then, we gradually introduced the system to employees, trained them, and supported the implementation process. We also developed custom business processes that were automated, including: management and control of export operations, internal documentation legalisation, contract approval routes and statuses. Now the company operates on a Bitrix24-based system where it\'s clear who is doing what and when. Every process is tracked, and important steps are no longer lost.</p>',
                'tm' => '<p>Ilki bilen kompaniýadaky häzirki iş proseslerini seljerdik: işler nähili gurnalýar, haýsy ýerlerde bökdençlik bolýar we haýsy wezipeler gaýtalanýar — şulary gözden geçirdik. Soňra Bitrix24 ulgamyny ornaşdyrmak boýunça ädimme-ädim meýilnama düzdük. Bir aýyň dowamynda bölümleriň ýolbaşçylary bilen her gün işleşdik: wezipeleriň ugruny, rol bölünişini we ylalaşyk ugurlaryny sazladyk. Şondan soň ulgamy tapgyrlaýyn işgärlere geçirdik, işläp ulanmaga öwretdik we ornaşdyrma tapgyryna goldaw berdik. Üstüne üstlük, ýöriteleşdirilen iş proseslerini hem awtomatlaşdyrdyk: eksport amallarynyň resmileşdirilişi we gözegçiligi, içki resminamalaryň ykrar edilmegi, şertnamalaryň ylalaşyk ugurlary we statuslary. Şu wagt kompaniýada Bitrix24 esasynda işleýän ulgam bar — kim näme edýär we haçan edýär diýen zatlar aýdyňdyr, ähli işler yzarlanýar we möhüm ädimler ýitirilmeýär.</p>'
            ],
            // Transcaspian Tours (ID: 125)
            125 => [
                'ru' => '<p>Мы провели первичную SEO-оптимизацию и подготовили сайт к выходу в поиск: Подключили Google Search Console — чтобы контролировать индексирование и ошибки; Настроили Google Analytics — для отслеживания трафика и поведения пользователей; Привели в порядок заголовки: настроили иерархию H1–H6, чтобы страницы лучше читались поисковиками; Переписали тексты с учётом релевантных ключевых запросов; Обновили meta-ключевые слова и описания; Запустили Google Ads-рекламу, чтобы сразу усилить трафик и протестировать интерес к предложениям. Сайт начал индексироваться, позиции улучшились, пошли первые переходы по рекламе и органике.</p>',
                'en' => '<p>We conducted initial SEO optimization and prepared the website for search visibility: Connected Google Search Console to monitor indexing and detect issues; Set up Google Analytics to track traffic and user behavior; Organized headings by configuring the H1–H6 hierarchy for better readability by search engines; Rewrote the content using relevant keywords; Updated meta keywords and descriptions; Launched Google Ads to boost traffic and test interest in the offers. The site started indexing, positions improved, and the first clicks came from both ads and organic search.</p>',
                'tm' => '<p>Biz başlangyç SEO optimizasiýasyny geçirdik we saýty gözleg ulgamlarynda peýda bolmagy üçin taýýarladyk: Google Search Console birleşdirdik — sahypanyň indekslenişini we tehniki ýalňyşlyklary gözegçilikde saklamak üçin; Google Analytics sazladyk — ulanyjylaryň traffigini we hereketini yzarlamak üçin; Baş sahypa ýazgylaryny tertipledik: H1–H6 derejesindäki sarlawgalary dogry ýerleşdirdik, sahypalaryň gözleg motorlary üçin has düşnükli bolmagy üçin; Tekstleri degişli açar sözlere görä täzeden ýazdyk; Meta beýany we açar sözleri täzeledik; Google Ads reklamalaryny başlatdyk — traffigi çalt artdyrmak we hödürlemelere gyzyklanmany synagdan geçirmek üçin. Netijede, sahypa indekslenmäge başlady, pozisiýalar gowulandy we ilkinji geçişler reklamadan hem-de organiki gözlegden peýda boldy.</p>'
            ],
            // Kenek (ID: 126)
            126 => [
                'ru' => '<p>Мы разработали мобильное приложение для Android и iOS, синхронизированное с текущей системой магазина. Реализовали: каталог с фильтрами, поиском и быстрым доступом к популярным товарам; карточки с фото, описанием и ценой; корзину и оформление заказа; push-уведомления для акций и напоминаний. Приложение успешно опубликовано в Google Play и App Store. Всё адаптировано под реальные сценарии использования: покупка в дороге, просмотр новинок, быстрый повторный заказ. Теперь у Kenek есть полноценный мобильный канал продаж — удобный, современный и готовый к масштабированию.</p>',
                'en' => '<p>We developed a mobile application for Android and iOS, fully synchronized with the client\'s existing store system. The app includes the following features: a catalog with filters, search, and quick access to popular products; product cards with photos, descriptions, and prices; a shopping cart and an easy checkout process; push notifications for promotions and reminders. The application was successfully published on both Google Play and the App Store. All features are adapted to real-life usage scenarios: shopping on the go, browsing new arrivals, and quickly reordering favorites. Now, Kenek has a full-fledged mobile sales channel — convenient, modern, and ready to scale.</p>',
                'tm' => '<p>Biz Android we iOS üçin mobil goşundyny taýýarladyk, ol dükan ulgamynyň häzirki ulgamy bilen doly sinhronizirlenen. Goşundyda aşakdaky mümkinçilikler üpjün edildi: filtrler, gözleg we meşhur harytlara çalt elýeterlilik bilen katalog; suratlar, düşündiriş we bahasy bilen haryt kartlary; sebet we sargyt etmek funksiýasy; aksiýalar we ýatlatmalar üçin push-bildirişler. Goşundy üstünlikli ýagdaýda Google Play hem-de App Store platformalaryna ýerleşdirildi. Ähli aýratynlyklar hakyky ulanmak ýagdaýlaryna uýgunlaşdyryldy: ýolda söwda etmek, täze gelen harytlara seretmek, tiz gaýtadan sargyt bermek. Indi Kenek markasynyň doly görnüşli mobil satuw kanaly bar — amatly, häzirki zaman talaplaryna laýyk we giňeldilmäge taýýar.</p>'
            ],
            // Colife Invest (ID: 127)
            127 => [
                'ru' => '<p>Мы внедрили Bitrix24 и адаптировали его под бизнес-процессы агентства: Настроили CRM-систему для брокеров, с чётким распределением сделок по стадиям и возможностью отслеживать прогресс по каждому клиенту; Подключили открытые линии и телефонию — все обращения с сайта, мессенджеров и звонки теперь фиксируются и привязываются к конкретным сделкам и сотрудникам; Реализовали аналитику по переговорам, задачам и эффективности брокеров, чтобы руководство видело реальные показатели работы; Настроили механизмы постановки и контроля задач, чтобы все этапы сделки велись в срок и без потерь информации. Теперь у Colife Invest — прозрачная система управления продажами, которая помогает контролировать клиентские коммуникации, эффективность команды и качество сопровождения на всех этапах.</p>',
                'en' => '<p>We implemented Bitrix24 and customized it to match the agency\'s business processes: Configured a CRM system for brokers with clearly defined deal stages and the ability to track progress for each client; Integrated open channels and telephony — all inquiries from the website, messengers, and phone calls are now logged and linked to specific deals and team members; Set up analytics for communications, tasks, and broker performance so that management can monitor actual results; Established task assignment and control mechanisms to ensure every stage of the deal is completed on time and without data loss. Now, Colife Invest has a transparent sales management system that helps monitor client communications, team performance, and service quality at every stage.</p>',
                'tm' => '<p>Biz Bitrix24 ulgamyny ornaşdyrdyk we ony agentligiň iş proseslerine laýyklykda uýgunlaşdyrdyk: Brokerler üçin CRM ulgamy sazlandy — geleşikleriň basgançaklara takyk bölünmegi üpjün edildi we her bir müşderiniň ösüşini yzarlaýmak mümkinçiligi döredildi; Açyk liniýalar we telefon aragatnaşygy birikdirildi — websaýtdan, messenjerlerden we telefonlardan gelen ähli ýüzlenmeler indi hasaba alynýar we degişli geleşikler hem-de işgärler bilen baglanyşdyrylýar; Gepleşikler, wezipeler we brokerleriň netijeliligi boýunça analitika ornaşdyryldy — bu ýolbaşçylyga hakyky iş görkeziji görkezijilere gözegçilik etmäge mümkinçilik berýär; Wezipeleri bellemek we ýerine ýetirilişini dolandyrmak mehanizmleri döredildi — munuň netijesinde her bir geleşik tapgyry wagtynda we maglumat ýitgisiz ýerine ýetirilýär. Häzirki wagtda Colife Invest kompaniýasynyň aç-açan satuw dolandyryş ulgamy bar. Bu ulgam müşderiler bilen aragatnaşygy, işgärleriň netijeliligini we hyzmatyň hilini her tapgyrda doly gözegçilikde saklamaga ýardam edýär.</p>'
            ],
            // Takyk Abzal (ID: 128)
            128 => [
                'ru' => '<p>Мы реализовали кастомную разработку на базе коробочного Битрикс24, полностью соответствующую логике клиента. 📌 Как работает система: Создаются роли (например, тренер, координатор, участник). К каждой роли привязываются пользователи — как штатные, так и внешние. Создаётся модуль, где указывается, какие роли требуются для его проведения. Из модулей формируются услуги — единицы тренинговой программы. Далее создаётся список компаний, которые участвуют в обучении. Создаётся тренинг: выбирается услуга, задаются даты, компании, количество участников и сумма оплаты. Для каждой компании указывается факт оплаты — это фиксируется в отдельном разделе, доступном только директору. После выбора услуги система автоматически подтягивает нужные модули, а внутри них — доступных пользователей по ролям. Важно: если у пользователя ранее не была задана роль (например, "лид-тренер"), система просто не даст выбрать его для модуля — это исключает ошибки. По итогу все тренинги отображаются в календаре. Видны даты, модули, роли, компании, участники — всё, кроме финансов, доступных только руководству компании. 📊 Что получили в итоге: Полная цифровая экосистема для управления тренингами; Исключение ошибок и "человеческого фактора"; Чёткое разграничение прав доступа: финансовая информация доступна только руководству; Гибкое масштабирование — можно добавлять новые роли, модули, услуги, компании; Упрощение работы всей команды, ускорение процессов, прозрачность в данных.</p>',
                'en' => '<p>We implemented a custom solution based on Bitrix24 that fully matches the client\'s logic. 📌 How the system works: Roles are created (e.g., trainer, coordinator, participant). Users — both internal and external — are assigned to these roles. A module is created, specifying which roles are required for its delivery. Modules are grouped into services — the core units of the training program. A list of companies participating in the training is created. A training session is scheduled: the service is selected, dates, companies, number of participants, and payment amount are set. Payment confirmation for each company is recorded in a separate section visible only to the director. Once a service is selected, the system automatically pulls in the required modules, and within them — the available users by role. Important: if a user does not have a pre-assigned role (e.g., "lead trainer"), the system simply will not allow them to be selected — this prevents errors. All training sessions are displayed in a calendar. Dates, modules, roles, companies, and participants are visible — everything except financial data. 📊 What we achieved: A fully digital ecosystem for managing training; Elimination of errors and the "human factor"; Clear access control: financial data is visible only to management; Flexible scalability — new roles, modules, services, and companies can be added; Simplified workflows for the entire team, faster processes, and transparent data.</p>',
                'tm' => '<p>Biz müşderiniň logikasyna doly laýyk gelýän Bitrix24 binyadyndaky ýöriteleşdirilen ulgam döretdik. 📌 Ulgamyň iş prinsipi: Rollar döredilýär (meselem: tälimçi, utgaşdyryjy, gatnaşýan). Bu rollara içki ýa-da daşarky ulanyjylar birikdirilýär. Modul döredilýär — bu ýerde haýsy rollaryň zerurdygy görkezilýär. Modulardan hyzmatlar düzülýär — okuw programmasynyň esasy birligi hökmünde. Okuwa gatnaşýan kompaniýalaryň sanawy döredilýär. Trening döredilýär: hyzmat saýlanylýar, seneler, kompaniýalar, gatnaşyjy sany we töleg mukdary görkezilýär. Her kompaniýa üçin töleg ýagdaýy aýratyn bölümde bellenýär — bu bölüme diňe direktor girip bilýär. Hyzmat saýlanandan soň, ulgam awtomatiki ýagdaýda degişli modulary we olardaky ulanyjylary (rollara görä) çekýär. Üstünlikli aýratynlyk: eger bir ulanyja öňünden belli bir rol (meselem, "baş tälimçi") berilmedik bolsa — ulgam onuň modula saýlanylmagyna ýol bermeýär. Bu bolsa ýalňyşlyklaryň öňüni alýar. Treningleriň ählisi senenamada (kalendar) görkezilýär. Seneler, modulalar, rollar, kompaniýalar we gatnaşyjylar — ählisi görünýär, diňe maliýe maglumatlary gizlin bolýar. 📊 Netijede alnan zatlar: Trening dolandyryşy üçin doly sanly ekoulgam; Ýalňyşlyklar we "adam faktory" doly ýok edildi; Girişiň anyk bölünmegi — maliýe maglumatlaryna diňe ýolbaşçylar girip bilýär; Giňeldilmäge taýyn gurluş — täze rollar, modulalar, hyzmatlar we kompaniýalar goşulyp bilýär; Toparyň işini ýeňilleşdirýän, prosesi çaltlaşdyrýan we aç-açan maglumatlary üpjün edýän ulgam.</p>'
            ],
            // Добавьте другие проекты по необходимости
        ];

        foreach ($portfolioResults as $portfolioId => $results) {
            foreach ($results as $locale => $result) {
                PortfolioTranslation::where('portfolio_id', $portfolioId)
                    ->where('locale', $locale)
                    ->update(['result' => $result]);
            }
        }

        $this->command->info('✅ Поле result успешно обновлено для портфолио!');
        $this->command->info('📊 Обновлено записей: ' . count($portfolioResults));
    }
}
